### ISSUE TITLE
VaadinContext#BeanStore does not support optional creates

### ISSUE THREAD

**Issue by CodingFabian** [tomivirkki/cdiutils#1]
Hi Tomi,
I am using CDI utils with great pleasure.
I noticed that there is a small gap in your implementation
In CDI you can declare an Observer of an event as optional if it is not existing:

 @Observes(notifyObserver = Reception.IF_EXISTS)

this works fine, up to the point where the VaadinContext implementation is hit:

```
            ContextualInstance<T> contextualInstance = (ContextualInstance<T>) instances
                    .get(bean);
            if (contextualInstance == null && creationalContext != null) {
                contextualInstance = new ContextualInstance<T>(
                        bean.create(creationalContext), creationalContext);
                addBeanInstance(bean, contextualInstance);
            }
            return contextualInstance.getInstance();
```

in instances null is returned. And because in those optional methods, the creationalContext is == null, we will not enter the bean.create block.
and then: NPE.

so getInstance() should only be returned when contextualInstance is not null, otherwise it should return null.

For reference:
ObserverMethod<T,X>.getReceiverIfExists()
and check how AbstractContext handles this part in get(Contextual,CreationalContext) [it has this return null if it cant find an instance and it has no creational context]

Would be happy to see an official version from you which fixes this.

**Comment by CodingFabian** [comment]
a patch in the spirit of weld style would be like this

```
        protected <T> T getBeanInstance(final Bean<T> bean,
                final CreationalContext<T> creationalContext) {
            ContextualInstance<T> contextualInstance = (ContextualInstance<T>) instances
                    .get(bean);
            if (contextualInstance != null) {
            return contextualInstance.getInstance();
            } else if (creationalContext != null) {
                contextualInstance = new ContextualInstance<T>(
                        bean.create(creationalContext), creationalContext);
                addBeanInstance(bean, contextualInstance);
                return contextualInstance.getInstance();
            } else {
            return null;
            }
        }
```

**Comment by tomivirkki** [comment]
Hello Fabian
Just pushed a fix for the issue you mentioned. Didn't notice your patch until now but I believe this can be considered fixed. Thanks for bringing this up :)

**Comment by CodingFabian** [comment]
great. are you planning to release a version for 6.8 to maven repo during the next days?

**Comment by tomivirkki** [comment]
Sure am. I'll release the 1.0 stable today or tomorrow.
