### ISSUE TITLE
Make VaadinContextImpl and getRequestData public

### ISSUE THREAD

**Issue by CodingFabian** [tomivirkki/cdiutils#2]
(or provide a better way to do this)

Hi Tomi,

In our app, we are starting a few async threads to do stuff. Because they need to access the beans of our user, we pass in our application to the new thread and make sure CDI is all set up.
This works great when doing ugly tricks like this

```
        Context context = Container.instance().deploymentManager()
            .getContext(VaadinScoped.class);
        // Hack because the VaadinContextImpl and the getRequestData are private
        Method requestDataGetter = context.getClass().getDeclaredMethod("getRequestData");
        requestDataGetter.setAccessible(true);
        RequestData requestData = (RequestData) requestDataGetter.invoke(context);
        // connect this threads VaadinContext with the application
        requestData.setApplication(application);
```

which is basically:
we get the VaadinContext for this thread from the CDI container. 
This is a fresh one and we would need to stick in our application we have, so this vaadin context knows where its beans are.
However both: the impl and access to the request data is hidden.
But thanks to reflection we can prepare this context so that it actually works :)

Note that the flow as such is not hacky. It is the same you do for regular web requests with onRequestStart in the application. with the slight difference that I need to prepare that before I work with any beans.

**Comment by tomivirkki** [comment]
I'm sure asynchronous threads can cause headache with the current implementation as it relies on RequestScoped data. Opened up the apis a bit so I guess this is fixed now.

Notice that I also published a CDI Utils implementation for Vaadin 7 earlier (new branch). I've dropped the whole RequestData-pattern and instead use (built-in) ThreadLocal Vaadin UI's to determine the BeanStore. As Vaadin 7.0 is still under development, I feel it's too early to publish it on Vaadin Directory yet.
