### ISSUE TITLE
ParameterDTO should allow checking for secondary parameters

### ISSUE THREAD

**Issue by CodingFabian** [tomivirkki/cdiutils#3]
Currently there is no nice way to check for secondary parameter with a specific index.

Right now we need to use the array getter, check it for null and length and can then do the index call. this should be handled somehow by the class.

**Comment by tomivirkki** [comment]
I improved ParameterDTO for version 1.1.0. getSecondaryParameter now checks for null and array length/index. the new method getSecondaryParametersList returns a non-null list including all the secondary parameters.
